version: 2.1

executors:
  default:
    docker: 
      - image: circleci/node:8
    shell: /bin/bash

jobs:
  version-alignment-rule:
    executor: default
    description: Control version alignment of packages across multiple repositories.
    parameters: 
      API_KEY:
        description: Enter either your datree api key or use the CircleCI UI to add your token under the 'DATREE_API_KEY' env var
        default: $DATREE_API_KEY
        type: string
      file_path:
        description: JSON formatted object including the expected an actual code component version. For more information view README file
        default: ''
        type: string
      payload:
        description: JSON formatted object including the expected an actual code component version. For more information view README file
        default: ''
        type: string
    steps:
      - checkout
      - run: 
          name: datree version-compare policy
          command: |
            npm install @datreeio/version-compare && \
            node ./node_modules/@datreeio/version-compare/index \
            -a << parameters.API_KEY >> \
            -f '<< parameters.file_path >>' \
            -p '<< parameters.payload >>' \
            -u $CIRCLE_PULL_REQUEST