version: 2.1

executors:
  default:
    docker: 
      - image: circleci/node:8
    shell: /bin/bash

jobs:
  compare-versions:
    executor: default
    description: 'this is compare-versions descriptions'
    parameters: 
      API_KEY:
        description: Enter either your datree api key or use the CircleCI UI to add your token under the 'DATREE_API_KEY' env var
        default: $DATREE_API_KEY
        type: string
      file_path:
        description: JSON formatted object including the expected an actual code component version. For more information view README file
        type: string
    steps:
      - checkout
      - run: 
          name: datree version-compare policy
          command: |
            npm install @datreeio/version-compare && \
            node ./node_modules/@datreeio/version-compare/index \
            -a << parameters.API_KEY >> \
            -f '<< parameters.file_path >>' \
            -u $CIRCLE_PULL_REQUEST